title: Bedrock Wiki
email: sirlich.business@gmail.com
description: >- 
  Knowledge-sharing Bedrock Wiki, containing documentation, tutorials, and general how-to information. Written and maintained by SirLich#1658.

remote_theme: pmarsceill/just-the-docs
color_scheme: light

github_username:  SirLich

coderay_default_lang: JSON
markdown: kramdown
url: https://wiki.bedrock.dev
aux_links:
  "Discord":
    - "https://discord.gg/XjV87YN"
  "Bedrock.dev":
    - "https://bedrock.dev/"
  "Contribute":
    - "https://github.com/SirLich/technical-bedrock"
  "Beginner Guide":
    - "https://guide.bedrock.dev/"

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

search_enabled: true
